Fixes #52
DSC-Banasthali-Vidyapith/Code-Crossroad pull request #64
Opened 2021-06-20 07:57 UTC by Riyamittal15

Fixes #52

2021-06-22 20:40 UTC, v-vanisha requested changes
You need to add at least two test cases for your code according to the said guidelines.

2021-06-23 10:17 UTC, Riyamittal15 commented
Recheck please, updated the code

2021-07-19 18:18 UTC, nimisha-yadav approved these changes

2021-07-19 19:50 UTC, v-vanisha approved these changes

2021-07-25 09:22 UTC, Vanshikagarg17 approved these changes

2021-07-25 09:22 UTC, merged