Fixes #59
DSC-Banasthali-Vidyapith/Code-Crossroad pull request #69
Opened 2021-06-21 17:13 UTC by Nimisha500

2021-07-25 10:52 UTC, sakshigoel19 requested changes
Hey @Nimisha500 ! Your code uses two passes to segregate 0s and 1s, can you optimize it to a single pass algorithm?

2021-08-07 15:37 UTC, sakshigoel19 approved these changes

2021-08-08 10:21 UTC, nimisha-yadav approved these changes

2021-08-10 11:16 UTC, v-vanisha approved these changes

2021-08-11 16:30 UTC, Vanshikagarg17 approved these changes

2021-08-11 16:30 UTC, merged