Added code for Intersection of two linked lists
DSC-Banasthali-Vidyapith/Code-Crossroad pull request #96
Opened 2021-07-30 07:48 UTC by SmritiOjha23

Fixes issue #85

2021-08-02 02:39 UTC, nimisha-yadav requested changes
Hey @SmritiOjha23, please explain your algorithm at the beginning of the code.

2021-08-02 06:30 UTC, SmritiOjha23 commented
@nimisha-yadav I have updated the file with the required changes. Please check.

2021-08-02 21:05 UTC, nimisha-yadav approved these changes
LGTM

2021-08-02 21:21 UTC, nimisha-yadav requested changes

2021-08-02 21:21 UTC, nimisha-yadav commented on Linked list/Intersection of Two Linked Lists.java
> +	public static void intersect(ListNode last1,ListNode last2, ListNode commonHead)
error: cannot find symbol [in __Driver__.java]

2021-08-02 21:27 UTC, nimisha-yadav requested changes
Error: Exception in thread "main"

2021-08-03 03:53 UTC, SmritiOjha23 commented
@nimisha-yadav The code runs without any errors on Java IDE's like Net beans and Eclipse. However, if a person runs this on online compilers like Codechef, one has to do a small amendment in the definition of the main function else it will throw a runtime error.

2021-08-03 04:04 UTC, SmritiOjha23 commented
@nimisha-yadav please check. I hope it works fine now.

2021-08-03 04:11 UTC, nimisha-yadav approved these changes
LGTM!

2021-08-03 10:19 UTC, Ananyaas approved these changes

2021-08-03 10:49 UTC, sakshigoel19 approved these changes

2021-08-07 11:31 UTC, v-vanisha approved these changes

2021-08-08 08:27 UTC, Vanshikagarg17 approved these changes

2021-08-08 08:27 UTC, merged