Fixes #77
DSC-Banasthali-Vidyapith/Code-Crossroad pull request #97
Opened 2021-08-01 05:26 UTC by SnehaAgarwal361

Added code for solve_the_sudoko.
Checklist:
 My code follows the style guidelines(Clean Code) of this project
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas
 My changes generate no new warnings

2021-08-01 05:48 UTC, SnehaAgarwal361 commented
@nimisha-yadav @Ananyaas  please review my pr

2021-08-02 02:23 UTC, nimisha-yadav requested changes
Hi @SnehaAgarwal361, your code looks good but as per guidelines, can you use 1tab/4space indentation?

2021-08-02 05:30 UTC, SnehaAgarwal361 commented
Please check now @nimisha-yadav

2021-08-02 14:27 UTC, Vanshikagarg17 approved these changes

2021-08-02 14:27 UTC, merged